name: Update posts & Notify to blog repo

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Update posts.json for all directories
        run: python .github/scripts/update_posts.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update posts' || true
          git push

  notify-to-blog-repo:
    runs-on: ubuntu-latest
    needs: update-posts

    steps:
      - name: Trigger blog repository workflow
        run: |
          curl -v -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_BLOG_REPO }}" \
            https://api.github.com/repos/jaclynfinnie/jaclynfinnie.github.io/dispatches \
            -d '{"event_type": "update_completed"}'
